### ISSUE TITLE
VS2019 Compatability

### ISSUE THREAD

**Issue by evanricard** [ymassad/PurityAnalyzer#10]
@ymassad hey Yacoub, I recently read your articles on dotnetcurry and wanted to try your extension in VS2019. I downloaded the .vsix file and was met with this curious error.

In any event, thanks!
![image](https://user-images.githubusercontent.com/30779615/71788816-e1cba700-2ff3-11ea-991f-08f4f3cf312e.png)

**Comment by ymassad** [comment]
Fixed and updated version to 0.8. Thanks @evanricard for reporting this.
