### ISSUE TITLE
Casting to object impure?

### ISSUE THREAD

**Issue by seerek** [ymassad/PurityAnalyzer#6]
While working on #5 I've tested latest (github) version of PurityAnalyzer and found strange behavior related to casting.

Given following code:
```cs
 [IsPure] private static string AliasWithNo(int number) => "test_" + number;
```

PurityAnalyzer underlined `number` and said:

> Cast is impure. 
> Error casting.
> From: System.Int32
> To: System.Object
> Relevant methods:  System.Object.ToString()

This make me notice that `int.ToString()` is impure but I don't understand why cast to object is impure?
Strangely enough changing `"test_" + number` to `$"test_{number}"` removes the error.

But, knowing that `int.ToString()` is impure I've changed it to `FormattableString.Invariant($"test_{number}")` and added 

> System.FormattableString, Invariant(System.FormattableString)
> System.FormattableString, ToString()

to PureMethods.txt
but then I've again received error
> Cast is impure. 
> Error casting.
> From: System.String
> To: System.FormattableString
> Relevant methods:  
> System.FormattableString.get_Format
> System.FormattableString.GetArguments
> System.FormattableString.get_ArgumentCount
> System.FormattableString.ToString
> System.FormattableString.ToString
> System.Object.GetHashCode

* Why is casting to object impure? (I guess because of impure ToString())
* How to resolve cases like above?
* is GetHashCode really impure?
* Or maybe it's just unfinished feature

**Comment by ymassad** [comment]
When casting, PurityAnalyzer will consider the case 'impure' if the target type has a virtual method that is pure, but the source type implementation (or override) of that method is impure.

For example:

```
object obj1 = 5;

var s = obj1.ToString();
```

The ToString method in Object is pure, but in Int32, it is impure.

If PruityAnalyzer allowed the cast, how should it treat `obj1.ToString()`? This is calling `Object.ToString()` which is pure. Should it try to know what is the 'real' type behind `obj1`? How long should the analysis be? What if `obj1` is a parameter in a method? Should we check all callers? What if the callers are not in the same assembly?

This is why I chose to create the concept of an 'impure cast'.

Regarding string interpolation, PurityAnalyzer still does not support this correctly. I will add some issues for that.

**Comment by ymassad** [comment]
I am closing this issue since #7 and #8 are done.
